#!/bin/sh

bindkey '^[[3~' delete-char # Delete
bindkey '^[[3;5~' kill-word # Ctrl + Delete
bindkey '^H' backward-kill-word # Ctrl + Backspace
bindkey '^[[1;5C' forward-word # Ctrl + Right
bindkey '^[[1;5D' backward-word # Ctrl + Left
bindkey '^[[H' beginning-of-line # Home
bindkey '^[[F' end-of-line # End
bindkey '^[[5~' beginning-of-buffer-or-history # Page Up
bindkey '^[[6~' end-of-buffer-or-history # Page Down
