#!/bin/sh

current_dir="$( dirname -- "${BASH_SOURCE[0]}"; )"
source $current_dir/../../.powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
