#!/bin/sh

__user_and_host="\[\033[01;32m\]\u@\h"
__cur_location="\[\033[01;34m\]\w"
__git_branch_color="\[\033[31m\]"
__git_branch='`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\ /`'
__prompt_tail="\[\033[35m\]$"
__last_color="\[\033[00m\]"

export PS1="$__user_and_host $__cur_location $__git_branch_color$__git_branch$__prompt_tail$__last_color "

