#!/bin/sh

current_dir="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"

for file in "$current_dir"/*
do
  [ "$file" != "$current_dir/rc" ] && . $file
done

zshrc_d="$HOME/.zshrc.d"
if [ -d "$zshrc_d" ]; then
  for file in "$zshrc_d"/*; do
    [ -f "$file" ] && . "$file"
  done
fi

bashrc_d="$HOME/.bashrc.d"
if [ -d "$bashrc_d" ]; then
  for file in "$bashrc_d"/*; do
    [ -f "$file" ] && . "$file"
  done
fi

return 0
